//! Approved 2026-09-08 Mage and Sorcerer ritual pixels.
//! Runtime sampling and persona substitution use the existing asset paths.
use super::{ClassArt, IndexedPaletteEntry, Rgb};

const MAGE_PALETTE: &[IndexedPaletteEntry] = &[
    IndexedPaletteEntry {
        key: 'o',
        colour: Some(Rgb::new(20, 16, 26)),
    },
    IndexedPaletteEntry {
        key: 'k',
        colour: Some(Rgb::new(128, 74, 52)),
    },
    IndexedPaletteEntry {
        key: 'K',
        colour: Some(Rgb::new(216, 148, 96)),
    },
    IndexedPaletteEntry {
        key: 'h',
        colour: Some(Rgb::new(250, 210, 150)),
    },
    IndexedPaletteEntry {
        key: 'c',
        colour: Some(Rgb::new(44, 30, 64)),
    },
    IndexedPaletteEntry {
        key: 'C',
        colour: Some(Rgb::new(86, 64, 124)),
    },
    IndexedPaletteEntry {
        key: 'l',
        colour: Some(Rgb::new(196, 160, 220)),
    },
    IndexedPaletteEntry {
        key: 'm',
        colour: Some(Rgb::new(172, 166, 150)),
    },
    IndexedPaletteEntry {
        key: 'M',
        colour: Some(Rgb::new(236, 232, 214)),
    },
    IndexedPaletteEntry {
        key: 'd',
        colour: Some(Rgb::new(78, 52, 34)),
    },
    IndexedPaletteEntry {
        key: 'D',
        colour: Some(Rgb::new(140, 92, 50)),
    },
    IndexedPaletteEntry {
        key: 'a',
        colour: Some(Rgb::new(198, 60, 58)),
    },
    IndexedPaletteEntry {
        key: 'e',
        colour: Some(Rgb::new(120, 240, 140)),
    },
    IndexedPaletteEntry {
        key: 'p',
        colour: Some(Rgb::new(200, 180, 137)),
    },
    IndexedPaletteEntry {
        key: 'P',
        colour: Some(Rgb::new(240, 223, 175)),
    },
    IndexedPaletteEntry {
        key: 's',
        colour: Some(Rgb::new(166, 78, 85)),
    },
];

#[rustfmt::skip]
const MAGE_WORKING_A: &[&str] = &[
    "..e.............",
    ".oMo....ooo.....",
    "oMMMo..ocCCo....",
    "oMoMo.ocCCCCco..",
    "oMMMoocCCCCCCco.",
    ".od..ocCKhhKKco.",
    ".od..ocCKoKKoCo.",
    ".od..ocCKKKKKco.",
    ".od..occcKKKcco.",
    ".od..ocCCCCCCco.",
    ".od...ocCCCCco..",
    ".od....ooooo....",
    ".od..ocCCCCco...",
    ".odKKocCKCcco...",
    ".od..ocCKMoeco..",
    ".od..ocCcMMmKKo.",
    ".od..ocCoMMMoco.",
    ".od..ocCCoooCco.",
    ".od...ollllllo..",
    "......oddddo....",
    ".....oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

#[rustfmt::skip]
const MAGE_WORKING_B: &[&str] = &[
    "..e.............",
    ".oMo....ooo.....",
    "oMMMo..ocCCo....",
    "oMoMo.ocCCCCco..",
    "oMMMoocCCCCCCco.",
    ".od..ocCKhhKKco.",
    ".od..ocCKoKKoCo.",
    ".od..ocCKKKKKco.",
    ".od..occcKKKcco.",
    ".od..ocCCCCCCco.",
    ".od...ocCCCCco..",
    ".od....ooooo....",
    ".od..ocCCCCco...",
    ".odKKocCKCcco...",
    ".od..ocCKKocco..",
    ".od..ocCcMeMKKo.",
    ".od..ocCoMMMoco.",
    ".od..ocCCoooCco.",
    ".od...ollllllo..",
    "......oddddo....",
    ".....oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

#[rustfmt::skip]
const MAGE_COUNSEL_RAISE: &[&str] = &[
    "..e.............",
    ".oMo....ooo.....",
    "oMMMo..ocCCo....",
    "oMoMo.ocCCCCco..",
    "oMMMoocCCCCCCco.",
    ".od..ocCKhhKKco.",
    ".od..ocCKoKKoCo.",
    ".od..ocCKKKKKco.",
    ".od..occcKKKcco.",
    ".od..ocCCCCCCco.",
    ".od...ocCCCCcoKh",
    ".od....ooooo..KK",
    ".od..ocCCCCcooo.",
    ".odKKocCCCCcco..",
    ".od..ocCKMoeco..",
    ".od..ocCcMMmKKo.",
    ".od..ocCoMMMoco.",
    ".od..ocCCoooCco.",
    ".od...ollllllo..",
    "......oddddo....",
    ".....oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

#[rustfmt::skip]
const MAGE_COUNSEL_WAIT: &[&str] = &[
    "..e.............",
    ".oMo....ooo.....",
    "oMMMo..ocCCo....",
    "oMoMo.ocCCCCco..",
    "oMMMoocCCCCCCco.",
    ".od..ocCKhhKKco.",
    ".od..ocCKoKKoCo.",
    ".od..ocCKKKKKco.",
    ".od..occcKKKcco.",
    ".od..ocCCCCCCco.",
    ".od...ocCCCCco..",
    ".od....ooooo....",
    ".od..ocCCCCco...",
    ".odKKocCCCCcco..",
    ".od..ocCCCocco..",
    ".od..ocCcMoMKKo.",
    ".od..ocCoMMMoco.",
    ".od..ocCCoooCco.",
    ".od...ollllllo..",
    "......oddddo....",
    ".....oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

#[rustfmt::skip]
const MAGE_SPOILS: &[&str] = &[
    "..e.............",
    ".oMo....ooo.....",
    "oMMMo..ocCCo....",
    "oMoMo.ocCCCCco..",
    "oMMMoocCCCCCCco.",
    ".od..ocCKhhKKco.",
    ".od..ocCKoKKoCo.",
    ".od..ocCKKKKKco.",
    ".od..occcKKKcco.",
    ".od..ocCCCCCCco.",
    ".od...ocCCCCco..",
    ".od....ooooo....",
    ".od..ocCCCCco...",
    ".odKKocCCCCcco..",
    ".od..ocoooooco..",
    ".od..ocKPpPKKo..",
    ".od..ocPPsPPco..",
    ".od..ocoooooCco.",
    ".od...ollllllo..",
    "......oddddo....",
    ".....oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

#[rustfmt::skip]
const MAGE_RESTING: &[&str] = &[
    "..e.............",
    ".oMo....ooo.....",
    "oMMMo..ocCCo....",
    "oMoMo.ocCCCCco..",
    "oMMMoocCCCCCCco.",
    ".od..ocCKhhKKco.",
    ".od..ocCKmKKmCo.",
    ".od..ocCKKKKKco.",
    ".od..occcKKKcco.",
    ".od..ocCCCCCCco.",
    ".od...ocCCCCco..",
    ".od....ooooo....",
    ".od..ocCCCCco...",
    ".odKKocCCCCcco..",
    ".od..ocCCCCCCco.",
    ".od..ocCKKKKCco.",
    ".od..ocCCKKCCco.",
    ".od..ocCCCCCCco.",
    ".od...ollllllo..",
    "......oddddo....",
    ".....oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

#[rustfmt::skip]
const MAGE_UNKNOWN: &[&str] = &[
    "..e.............",
    ".oMo....ooo.....",
    "oMMMo..ocCCo....",
    "oMoMo.ocCCCCco..",
    "oMMMoocCCCCCCco.",
    ".od..ocCKhhKKco.",
    ".od..ocCKoKKoCo.",
    ".od..ocCKKKKKco.",
    ".od..occcKKKcco.",
    ".od..ocCCCCCCco.",
    ".od...ocCCCCco..",
    ".od....ooooo....",
    ".od..ocCCCCco...",
    ".odKKocCCCCcco..",
    ".od..ocCCCCCCco.",
    ".od..ocCCCCCCco.",
    ".od..ocCCCCCKKo.",
    ".od..ocCCCCCCco.",
    ".od...ollllllo..",
    "......oddddo....",
    ".....oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

#[rustfmt::skip]
const MAGE_SETTLED: &[&str] = &[
    "..e.............",
    ".oMo....ooo.....",
    "oMMMo..ocCCo....",
    "oMoMo.ocCCCCco..",
    "oMMMoocCCCCCCco.",
    ".od..ocCKhhKKco.",
    ".od..ocCKoKKoCo.",
    ".od..ocCKKKKKco.",
    ".od..occcKKKcco.",
    ".od..ocCCCCCCco.",
    ".od...ocCCCCco..",
    ".od....ooooo....",
    ".od..ocCCCCco...",
    ".odKKocCCCCcco..",
    ".od..ocCCCCCCco.",
    ".od..ocCCCCCKKo.",
    ".od..ocCCCCCCco.",
    ".od..ocCCCCCCco.",
    ".od...ollllllooo",
    "......oddddo.PsP",
    ".....oDd..dDoopo",
    ".....ooo..ooo...",
    "................",
    "................",
];

pub(super) const MAGE: ClassArt = ClassArt {
    palette: MAGE_PALETTE,
    frames: [
        MAGE_WORKING_A,
        MAGE_WORKING_B,
        MAGE_COUNSEL_RAISE,
        MAGE_COUNSEL_WAIT,
        MAGE_SPOILS,
        MAGE_RESTING,
        MAGE_UNKNOWN,
        MAGE_SETTLED,
    ],
    roster: None,
};

const SORCERER_PALETTE: &[IndexedPaletteEntry] = &[
    IndexedPaletteEntry {
        key: 'o',
        colour: Some(Rgb::new(26, 24, 34)),
    },
    IndexedPaletteEntry {
        key: 'k',
        colour: Some(Rgb::new(150, 96, 62)),
    },
    IndexedPaletteEntry {
        key: 'K',
        colour: Some(Rgb::new(238, 174, 118)),
    },
    IndexedPaletteEntry {
        key: 'h',
        colour: Some(Rgb::new(255, 226, 170)),
    },
    IndexedPaletteEntry {
        key: 'r',
        colour: Some(Rgb::new(168, 122, 44)),
    },
    IndexedPaletteEntry {
        key: 'R',
        colour: Some(Rgb::new(240, 200, 96)),
    },
    IndexedPaletteEntry {
        key: 'c',
        colour: Some(Rgb::new(78, 68, 116)),
    },
    IndexedPaletteEntry {
        key: 'C',
        colour: Some(Rgb::new(150, 142, 196)),
    },
    IndexedPaletteEntry {
        key: 'l',
        colour: Some(Rgb::new(240, 216, 140)),
    },
    IndexedPaletteEntry {
        key: 'm',
        colour: Some(Rgb::new(198, 190, 210)),
    },
    IndexedPaletteEntry {
        key: 'M',
        colour: Some(Rgb::new(248, 246, 255)),
    },
    IndexedPaletteEntry {
        key: 'd',
        colour: Some(Rgb::new(90, 60, 38)),
    },
    IndexedPaletteEntry {
        key: 'D',
        colour: Some(Rgb::new(156, 104, 56)),
    },
    IndexedPaletteEntry {
        key: 'a',
        colour: Some(Rgb::new(96, 168, 226)),
    },
    IndexedPaletteEntry {
        key: 'e',
        colour: Some(Rgb::new(255, 236, 150)),
    },
    IndexedPaletteEntry {
        key: 'p',
        colour: Some(Rgb::new(200, 180, 137)),
    },
    IndexedPaletteEntry {
        key: 'P',
        colour: Some(Rgb::new(240, 223, 175)),
    },
    IndexedPaletteEntry {
        key: 's',
        colour: Some(Rgb::new(166, 78, 85)),
    },
];

#[rustfmt::skip]
const SORCERER_WORKING_A: &[&str] = &[
    "...oooooooo.....",
    "...oeeeeeeo.....",
    "...oooooooo.....",
    "................",
    "....ooooooo.....",
    "...orRRRRRro....",
    "...orKhKhKro....",
    "...oKKoKKoKo....",
    "...oKKKKKKKo....",
    "...oKKKhKKKo....",
    "....oKKKKKo.....",
    ".....ooooo......",
    "....ocCCCCco....",
    "...ocCKCCKcco...",
    "...ocKKMmMKco...",
    "...ocCMoeoMCco..",
    "...ocCcmMmCCco..",
    "...ocCCCCCCCco..",
    "....olllllllo...",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

#[rustfmt::skip]
const SORCERER_WORKING_B: &[&str] = &[
    "...oooooooo.....",
    "...oeeeeeeo.....",
    "...oooooooo.....",
    "................",
    "....ooooooo.....",
    "...orRRRRRro....",
    "...orKhKhKro....",
    "...oKKoKKoKo....",
    "...oKKKKKKKo....",
    "...oKKKhKKKo....",
    "....oKKKKKo.....",
    ".....ooooo......",
    "....ocCCCCco....",
    "...ocCKCCKcco...",
    "...ocKKmmmKco...",
    "...ocCmoeomCco..",
    "...ocCcMMmCCco..",
    "...ocCCCCCCCco..",
    "....olllllllo...",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

#[rustfmt::skip]
const SORCERER_COUNSEL_RAISE: &[&str] = &[
    "...oooooooo.....",
    "...oeeeeeeo.....",
    "...oooooooo.....",
    "................",
    "....ooooooo.....",
    "...orRRRRRro....",
    "...orKhKhKro....",
    "...oKKoKKoKo....",
    "...oKKKKKKKo....",
    "...oKKKhKKKo....",
    ".Kh.oKKKKKo.....",
    ".KK..ooooo......",
    "..ooocCCCCco....",
    "...ocCCCCKcco...",
    "...ocKKMmMKco...",
    "...ocCMoeoMCco..",
    "...ocCcmMmCCco..",
    "...ocCCCCCCCco..",
    "....olllllllo...",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

#[rustfmt::skip]
const SORCERER_COUNSEL_WAIT: &[&str] = &[
    "...oooooooo.....",
    "...oeeeeeeo.....",
    "...oooooooo.....",
    "................",
    "....ooooooo.....",
    "...orRRRRRro....",
    "...orKhKhKro....",
    "...oKKoKKoKo....",
    "...oKKKKKKKo....",
    "...oKKKhKKKo....",
    "....oKKKKKo.....",
    ".....ooooo......",
    "....ocCCCCco....",
    "...ocCCCCKcco...",
    "...ocCCMmMKco...",
    "...ocCMoeoMCco..",
    "...ocCcmMmCCco..",
    "...ocCCCCCCCco..",
    "....olllllllo...",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

#[rustfmt::skip]
const SORCERER_SPOILS: &[&str] = &[
    "...oooooooo.....",
    "...oeeeeeeo.....",
    "...oooooooo.....",
    "................",
    "....ooooooo.....",
    "...orRRRRRro....",
    "...orKhKhKro....",
    "...oKKoKKoKo....",
    "...oKKKKKKKo....",
    "...oKKKhKKKo....",
    "....oKKKKKo.....",
    ".....ooooo......",
    "....ocCCCCco....",
    "...ocCCCCCCco...",
    "...ocKooooKco...",
    "...ocKPPPPKCco..",
    "...ocCPssPCCco..",
    "...ocCooooCCco..",
    "....olllllllo...",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

#[rustfmt::skip]
const SORCERER_RESTING: &[&str] = &[
    "...oooooooo.....",
    "...oeeeeeeo.....",
    "...oooooooo.....",
    "................",
    "....ooooooo.....",
    "...orRRRRRro....",
    "...orKhKhKro....",
    "...oKKmKKmKo....",
    "...oKKKKKKKo....",
    "...oKKKhKKKo....",
    "....oKKKKKo.....",
    ".....ooooo......",
    "....ocCCCCco....",
    "...ocCCCCCCco...",
    "...ocCCCCCCco...",
    "...ocCKKKKCCco..",
    "...ocCCKKCCCco..",
    "...ocCCCCCCCco..",
    "....olllllllo...",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

#[rustfmt::skip]
const SORCERER_UNKNOWN: &[&str] = &[
    "...oooooooo.....",
    "...oeeeeeeo.....",
    "...oooooooo.....",
    "................",
    "....ooooooo.....",
    "...orRRRRRro....",
    "...orKhKhKro....",
    "...oKKoKKoKo....",
    "...oKKKKKKKo....",
    "...oKKKhKKKo....",
    "....oKKKKKo.....",
    ".....ooooo......",
    "....ocCCCCco....",
    "...ocCCCCCCco...",
    "...ocCCCCCCco...",
    "...ocKCCCCCCco..",
    "...ocKKCCCCKco..",
    "...ocCCCCCCCco..",
    "....olllllllo...",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

#[rustfmt::skip]
const SORCERER_SETTLED: &[&str] = &[
    "...oooooooo.....",
    "...oeeeeeeo.....",
    "...oooooooo.....",
    "................",
    "....ooooooo.....",
    "...orRRRRRro....",
    "...orKhKhKro....",
    "...oKKoKKoKo....",
    "...oKKKKKKKo....",
    "...oKKKhKKKo....",
    "....oKKKKKo.....",
    ".....ooooo......",
    "....ocCCCCco....",
    "...ocCCCCCCco...",
    "...ocCCCCCCco...",
    "...ocKCCCCCKco..",
    "...ocKKCCCKKco..",
    "...ocCCCCCCCco..",
    "....ollllllloooo",
    ".....oddddo..PsP",
    "....oDd..dDo.opo",
    "....ooo..ooo....",
    "................",
    "................",
];

pub(super) const SORCERER: ClassArt = ClassArt {
    palette: SORCERER_PALETTE,
    frames: [
        SORCERER_WORKING_A,
        SORCERER_WORKING_B,
        SORCERER_COUNSEL_RAISE,
        SORCERER_COUNSEL_WAIT,
        SORCERER_SPOILS,
        SORCERER_RESTING,
        SORCERER_UNKNOWN,
        SORCERER_SETTLED,
    ],
    roster: None,
};
