//! Approved 2026-09-08 Cleric, Paladin and Druid ritual pixels.
//! Runtime sampling and persona substitution use the existing asset paths.
use super::{ClassArt, IndexedPaletteEntry, Rgb};

const CLERIC_PALETTE: &[IndexedPaletteEntry] = &[
    IndexedPaletteEntry {
        key: 'o',
        colour: Some(Rgb::new(24, 25, 32)),
    },
    IndexedPaletteEntry {
        key: 'k',
        colour: Some(Rgb::new(139, 82, 52)),
    },
    IndexedPaletteEntry {
        key: 'K',
        colour: Some(Rgb::new(232, 164, 103)),
    },
    IndexedPaletteEntry {
        key: 'h',
        colour: Some(Rgb::new(255, 224, 164)),
    },
    IndexedPaletteEntry {
        key: 'c',
        colour: Some(Rgb::new(43, 80, 137)),
    },
    IndexedPaletteEntry {
        key: 'C',
        colour: Some(Rgb::new(72, 126, 195)),
    },
    IndexedPaletteEntry {
        key: 'v',
        colour: Some(Rgb::new(126, 181, 230)),
    },
    IndexedPaletteEntry {
        key: 'w',
        colour: Some(Rgb::new(177, 181, 188)),
    },
    IndexedPaletteEntry {
        key: 'W',
        colour: Some(Rgb::new(239, 234, 216)),
    },
    IndexedPaletteEntry {
        key: 'l',
        colour: Some(Rgb::new(232, 184, 69)),
    },
    IndexedPaletteEntry {
        key: 'L',
        colour: Some(Rgb::new(255, 224, 116)),
    },
    IndexedPaletteEntry {
        key: 'm',
        colour: Some(Rgb::new(112, 91, 58)),
    },
    IndexedPaletteEntry {
        key: 'M',
        colour: Some(Rgb::new(193, 159, 84)),
    },
    IndexedPaletteEntry {
        key: 'd',
        colour: Some(Rgb::new(101, 60, 36)),
    },
    IndexedPaletteEntry {
        key: 'D',
        colour: Some(Rgb::new(166, 105, 52)),
    },
    IndexedPaletteEntry {
        key: 'e',
        colour: Some(Rgb::new(83, 224, 238)),
    },
    IndexedPaletteEntry {
        key: 'E',
        colour: Some(Rgb::new(193, 249, 243)),
    },
    IndexedPaletteEntry {
        key: 'p',
        colour: Some(Rgb::new(200, 180, 137)),
    },
    IndexedPaletteEntry {
        key: 'P',
        colour: Some(Rgb::new(240, 223, 175)),
    },
    IndexedPaletteEntry {
        key: 's',
        colour: Some(Rgb::new(166, 78, 85)),
    },
];

const CLERIC_WORKING_A: &[&str] = &[
    "................",
    ".e..............",
    "oEo...oooooo....",
    "oMo..owWWWWwo...",
    ".m..owWWWWWWwo..",
    ".m..owWwwwwWwo..",
    ".m..owKhhKKKwo..",
    ".m..owKoKKoKwo..",
    ".m..owKKKKKKwo..",
    ".m..owKKhhKKwo..",
    ".m...owWWWWwo...",
    ".m....oooooo....",
    ".m..ocCCClCCco..",
    ".m..ocKCCoPPlPo.",
    ".m..ocKKCoPplPo.",
    ".m..ocCCKoPplPo.",
    ".m...ocCCoPPlPo.",
    ".m...ocCCollLlo.",
    ".m...olllllloo..",
    ".m....oddddo....",
    ".M...oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const CLERIC_WORKING_B: &[&str] = &[
    "................",
    ".e..............",
    "oEo...oooooo....",
    "oMo..owWWWWwo...",
    ".m..owWWWWWWwo..",
    ".m..owWwwwwWwo..",
    ".m..owKhhKKKwo..",
    ".m..owKoKKoKwo..",
    ".m..owKKKKKKwo..",
    ".m..owKKhhKKwo..",
    ".m...owWWWWwo...",
    ".m....oooooo....",
    ".m..ocCCClCCco..",
    ".m..ocKCCoPPlPo.",
    ".m..ocKCCoPplPo.",
    ".m..ocKKCoPplPo.",
    ".m...ocCKoPPlPo.",
    ".m...ocCCollLlo.",
    ".m...olllllloo..",
    ".m....oddddo....",
    ".M...oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const CLERIC_COUNSEL_RAISE: &[&str] = &[
    "................",
    ".e..............",
    "oEo...oooooo....",
    "oMo..owWWWWwo...",
    ".m..owWWWWWWwo..",
    ".m..owWwwwwWwo..",
    ".m..owKhhKKKwo..",
    ".m..owKoKKoKwo..",
    ".m..owKKKKKKwo..",
    ".m..owKKhhKKwo..",
    ".mKh.owWWWWwo...",
    ".mKK..oooooo....",
    ".m.oocCCClCCco..",
    ".mKKocCCCoPPlPo.",
    ".m..ocCCCoPplPo.",
    ".m..ocCCKoPplPo.",
    ".m...ocCCoPPlPo.",
    ".m...ocCCollLlo.",
    ".m...olllllloo..",
    ".m....oddddo....",
    ".M...oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const CLERIC_COUNSEL_WAIT: &[&str] = &[
    "................",
    ".e..............",
    "oEo...oooooo....",
    "oMo..owWWWWwo...",
    ".m..owWWWWWWwo..",
    ".m..owWwwwwWwo..",
    ".m..owKhhKKKwo..",
    ".m..owKoKKoKwo..",
    ".m..owKKKKKKwo..",
    ".m..owKKhhKKwo..",
    ".m...owWWWWwo...",
    ".m....oooooo....",
    ".m..ocCCClCCco..",
    ".mKKocCCCoPPlPo.",
    ".m..ocCCCoPplPo.",
    ".m..ocCCKoPplPo.",
    ".m...ocCCoPPlPo.",
    ".m...ocCCollLlo.",
    ".m...olllllloo..",
    ".m....oddddo....",
    ".M...oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const CLERIC_SPOILS: &[&str] = &[
    "................",
    ".e..............",
    "oEo...oooooo....",
    "oMo..owWWWWwo...",
    ".m..owWWWWWWwo..",
    ".m..owWwwwwWwo..",
    ".m..owKhhKKKwo..",
    ".m..owKoKKoKwo..",
    ".m..owKKKKKKwo..",
    ".m..owKKhhKKwo..",
    ".m...owWWWWwo...",
    ".m....oooooo....",
    ".m..ocCCClCCco..",
    ".mKKocCCCollllo.",
    ".m..ocCCKolCClo.",
    ".m..ocCCCossClo.",
    ".m...ocCColCClo.",
    ".m...ocCCollLlo.",
    ".m...olllllloo..",
    ".m....oddddo....",
    ".M...oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const CLERIC_RESTING: &[&str] = &[
    "................",
    ".e..............",
    "oEo...oooooo....",
    "oMo..owWWWWwo...",
    ".m..owWWWWWWwo..",
    ".m..owWwwwwWwo..",
    ".m..owKhhKKKwo..",
    ".m..owKoKKoKwo..",
    ".m..owKKKKKKwo..",
    ".m..owKKhhKKwo..",
    ".m...owWWWWwo...",
    ".m....oooooo....",
    ".m..ocCCClCCco..",
    ".mKKocCCCoPPlPo.",
    ".m..ocCCCoPplPo.",
    ".m..ocCCKoPplPo.",
    ".m...ocCCoPPlPo.",
    ".m...ocCCollLlo.",
    ".m...olllllloo..",
    ".m....oddddo....",
    ".M...oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const CLERIC_UNKNOWN: &[&str] = &[
    "................",
    ".e..............",
    "oEo...oooooo....",
    "oMo..owWWWWwo...",
    ".m..owWWWWWWwo..",
    ".m..owWwwwwWwo..",
    ".m..owKhhKKKwo..",
    ".m..owKoKKKKwo..",
    ".m..owKKKKoKwo..",
    ".m..owKKhhKKwo..",
    ".m...owWWWWwo...",
    ".m....oooooo....",
    ".m..ocCCClCCco..",
    ".mKKocCCCoPPlPo.",
    ".m..ocCCCoPplPo.",
    ".m..ocCCKoPplPo.",
    ".m...ocCCoPPlPo.",
    ".m...ocCCollLlo.",
    ".m...olllllloo..",
    ".m....oddddo....",
    ".M...oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const CLERIC_SETTLED: &[&str] = &[
    "................",
    ".e..............",
    "oEo...oooooo....",
    "oMo..owWWWWwo...",
    ".m..owWWWWWWwo..",
    ".m..owWwwwwWwo..",
    ".m..owKhhKKKwo..",
    ".m..owKoKKoKwo..",
    ".m..owKKKKKKwo..",
    ".m..owKKhhKKwo..",
    ".m...owWWWWwo...",
    ".m....oooooo....",
    ".m..ocCCClCCco..",
    ".mKKocCCClCCco..",
    ".m..ocCCCCCCco..",
    ".m..ocKCCCCKco..",
    ".m...ocCCCCco...",
    ".m...ocCCCCco...",
    ".m...olllllloo..",
    ".m.llloddddo....",
    ".M.lsLDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

pub(super) const CLERIC: ClassArt = ClassArt {
    palette: CLERIC_PALETTE,
    frames: [
        CLERIC_WORKING_A,
        CLERIC_WORKING_B,
        CLERIC_COUNSEL_RAISE,
        CLERIC_COUNSEL_WAIT,
        CLERIC_SPOILS,
        CLERIC_RESTING,
        CLERIC_UNKNOWN,
        CLERIC_SETTLED,
    ],
    roster: None,
};

const PALADIN_PALETTE: &[IndexedPaletteEntry] = &[
    IndexedPaletteEntry {
        key: 'o',
        colour: Some(Rgb::new(27, 23, 27)),
    },
    IndexedPaletteEntry {
        key: 'k',
        colour: Some(Rgb::new(143, 78, 47)),
    },
    IndexedPaletteEntry {
        key: 'K',
        colour: Some(Rgb::new(231, 153, 91)),
    },
    IndexedPaletteEntry {
        key: 'h',
        colour: Some(Rgb::new(255, 218, 147)),
    },
    IndexedPaletteEntry {
        key: 'r',
        colour: Some(Rgb::new(74, 42, 31)),
    },
    IndexedPaletteEntry {
        key: 'R',
        colour: Some(Rgb::new(126, 68, 43)),
    },
    IndexedPaletteEntry {
        key: 'c',
        colour: Some(Rgb::new(37, 69, 120)),
    },
    IndexedPaletteEntry {
        key: 'C',
        colour: Some(Rgb::new(64, 112, 179)),
    },
    IndexedPaletteEntry {
        key: 'w',
        colour: Some(Rgb::new(139, 150, 154)),
    },
    IndexedPaletteEntry {
        key: 'W',
        colour: Some(Rgb::new(218, 224, 215)),
    },
    IndexedPaletteEntry {
        key: 'l',
        colour: Some(Rgb::new(236, 180, 62)),
    },
    IndexedPaletteEntry {
        key: 'L',
        colour: Some(Rgb::new(255, 220, 105)),
    },
    IndexedPaletteEntry {
        key: 'm',
        colour: Some(Rgb::new(119, 126, 128)),
    },
    IndexedPaletteEntry {
        key: 'M',
        colour: Some(Rgb::new(206, 214, 207)),
    },
    IndexedPaletteEntry {
        key: 'd',
        colour: Some(Rgb::new(92, 55, 34)),
    },
    IndexedPaletteEntry {
        key: 'D',
        colour: Some(Rgb::new(157, 93, 45)),
    },
    IndexedPaletteEntry {
        key: 'a',
        colour: Some(Rgb::new(211, 52, 50)),
    },
    IndexedPaletteEntry {
        key: 'e',
        colour: Some(Rgb::new(255, 241, 172)),
    },
    IndexedPaletteEntry {
        key: 'p',
        colour: Some(Rgb::new(200, 180, 137)),
    },
    IndexedPaletteEntry {
        key: 'P',
        colour: Some(Rgb::new(240, 223, 175)),
    },
    IndexedPaletteEntry {
        key: 's',
        colour: Some(Rgb::new(166, 78, 85)),
    },
];

const PALADIN_WORKING_A: &[&str] = &[
    "..MMM...........",
    ".MwwMM..........",
    ".oMwo.oooooo....",
    "..D..orRRRRro...",
    "..D.orRRRRRRro..",
    "..D.orRKKKKRro..",
    "..D.orKhhKKKro..",
    "..D.orKoKKoKro..",
    "..D.orKKKKKKro..",
    "..D.orKKhhKKro..",
    "..D..orRRRRro...",
    "..D...orRRro....",
    "..D.oomMMMMmoo..",
    "..D.omMwwMolloo.",
    "..D.omMKwKolCClo",
    "..D.omMMwMolCLlo",
    "..D..omMwoDlCClo",
    "..D..ocCCoolClo.",
    "..D..olllllolo..",
    "..D...oddddo....",
    "..D..oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const PALADIN_WORKING_B: &[&str] = &[
    "..MMM...........",
    ".MwwMM..........",
    ".oMwo.oooooo....",
    "..D..orRRRRro...",
    "..D.orRRRRRRro..",
    "..D.orRKKKKRro..",
    "..D.orKhhKKKro..",
    "..D.orKoKKoKro..",
    "..D.orKKKKKKro..",
    "..D.orKKhhKKro..",
    "..D..orRRRRro...",
    "..D...orRRro....",
    "..D.oomMMMMmoo..",
    "..D.omMwwMolloo.",
    "..D.omMwwMolCClo",
    "..D.omMKwKolCLlo",
    "..D..omMwKDlCClo",
    "..D..ocCCoolClo.",
    "..D..olllllolo..",
    "..D...oddddo....",
    "..D..oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const PALADIN_COUNSEL_RAISE: &[&str] = &[
    "..MMM...........",
    ".MwwMM..........",
    ".oMwo.oooooo....",
    "..D..orRRRRro...",
    "..D.orRRRRRRro..",
    "..D.orRKKKKRro..",
    "..D.orKhhKKKro..",
    "..D.orKoKKoKro..",
    "..D.orKKKKKKro..",
    "..D.orKKhhKKro..",
    ".Kh..orRRRRro...",
    ".KK...orRRro....",
    "..ooomMMMMmoo...",
    "..D.omMwwMolloo.",
    "..D.omMwwMolCClo",
    "..D.omMMwMolCLlo",
    "..D..omMwoDlCClo",
    "..D..ocCCoolClo.",
    "..D..olllllolo..",
    "..D...oddddo....",
    "..D..oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const PALADIN_COUNSEL_WAIT: &[&str] = &[
    "..MMM...........",
    ".MwwMM..........",
    ".oMwo.oooooo....",
    "..D..orRRRRro...",
    "..D.orRRRRRRro..",
    "..D.orRKKKKRro..",
    "..D.orKhhKKKro..",
    "..D.orKoKKoKro..",
    "..D.orKKKKKKro..",
    "..D.orKKhhKKro..",
    "..D..orRRRRro...",
    "..D...orRRro....",
    "..D.oomMMMMmoo..",
    "..DKomMwwMolloo.",
    "..D.omMwwMolCClo",
    "..D.omMMwMolCLlo",
    "..D..omMwoDlCClo",
    "..D..ocCCoolClo.",
    "..D..olllllolo..",
    "..D...oddddo....",
    "..D..oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const PALADIN_SPOILS: &[&str] = &[
    "..MMM...........",
    ".MwwMM..........",
    ".oMwo.oooooo....",
    "..D..orRRRRro...",
    "..D.orRRRRRRro..",
    "..D.orRKKKKRro..",
    "..D.orKhhKKKro..",
    "..D.orKoKKoKro..",
    "..D.orKKKKKKro..",
    "..D.orKKhhKKro..",
    "..D..orRRRRro...",
    "..D...orRRro....",
    "..D.oomMMMMmoo..",
    "..DKomMwwMolloo.",
    "..D.omMwwMolCClo",
    "..D.omMwwKossClo",
    "..D..omMwoDlCClo",
    "..D..ocCCoolClo.",
    "..D..olllllolo..",
    "..D...oddddo....",
    "..D..oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const PALADIN_RESTING: &[&str] = &[
    "..MMM...........",
    ".MwwMM..........",
    ".oMwo.oooooo....",
    "..D..orRRRRro...",
    "..D.orRRRRRRro..",
    "..D.orRKKKKRro..",
    "..D.orKhhKKKro..",
    "..D.orKoKKoKro..",
    "..D.orKKKKKKro..",
    "..D.orKKhhKKro..",
    "..D..orRRRRro...",
    "..D...orRRro....",
    "..D.oomMMMMmoo..",
    "..DKomMwwMolloo.",
    "..D.omMwwMolCClo",
    "..D.omMMwMolCLlo",
    "..D..omMwoDlCClo",
    "..D..ocCCoolClo.",
    "..D..olllllolo..",
    "..D...oddddo....",
    "..D..oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const PALADIN_UNKNOWN: &[&str] = &[
    "..MMM...........",
    ".MwwMM..........",
    ".oMwo.oooooo....",
    "..D..orRRRRro...",
    "..D.orRRRRRRro..",
    "..D.orRKKKKRro..",
    "..D.orKhhKKKro..",
    "..D.orKoKKKKro..",
    "..D.orKKKKoKro..",
    "..D.orKKhhKKro..",
    "..D..orRRRRro...",
    "..D...orRRro....",
    "..D.oomMMMMmoo..",
    "..DKomMwwMolloo.",
    "..D.omMwwMolCClo",
    "..D.omMMwMolCLlo",
    "..D..omMwoDlCClo",
    "..D..ocCCoolClo.",
    "..D..olllllolo..",
    "..D...oddddo....",
    "..D..oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const PALADIN_SETTLED: &[&str] = &[
    "..MMM...........",
    ".MwwMM..........",
    ".oMwo.oooooo....",
    "..D..orRRRRro...",
    "..D.orRRRRRRro..",
    "..D.orRKKKKRro..",
    "..D.orKhhKKKro..",
    "..D.orKoKKoKro..",
    "..D.orKKKKKKro..",
    "..D.orKKhhKKro..",
    "..D..orRRRRro...",
    "..D...orRRro....",
    "..D.oomMMMMmoo..",
    "..D.omMwwMMmmo..",
    "..D.omMwwMMmmo..",
    "..D.omKwwMMKmo..",
    "..D..omMMMMmo...",
    "..D..ocCCCCco...",
    "..D..olllllloooo",
    "..D...oddddo.lCl",
    "..D..oDd..dDoLsl",
    ".....ooo..ooo...",
    "................",
    "................",
];

pub(super) const PALADIN: ClassArt = ClassArt {
    palette: PALADIN_PALETTE,
    frames: [
        PALADIN_WORKING_A,
        PALADIN_WORKING_B,
        PALADIN_COUNSEL_RAISE,
        PALADIN_COUNSEL_WAIT,
        PALADIN_SPOILS,
        PALADIN_RESTING,
        PALADIN_UNKNOWN,
        PALADIN_SETTLED,
    ],
    roster: None,
};

const DRUID_PALETTE: &[IndexedPaletteEntry] = &[
    IndexedPaletteEntry {
        key: 'o',
        colour: Some(Rgb::new(22, 20, 26)),
    },
    IndexedPaletteEntry {
        key: 'c',
        colour: Some(Rgb::new(35, 68, 38)),
    },
    IndexedPaletteEntry {
        key: 'C',
        colour: Some(Rgb::new(65, 116, 55)),
    },
    IndexedPaletteEntry {
        key: 'v',
        colour: Some(Rgb::new(117, 162, 69)),
    },
    IndexedPaletteEntry {
        key: 'k',
        colour: Some(Rgb::new(134, 77, 51)),
    },
    IndexedPaletteEntry {
        key: 'K',
        colour: Some(Rgb::new(225, 153, 99)),
    },
    IndexedPaletteEntry {
        key: 'h',
        colour: Some(Rgb::new(255, 218, 151)),
    },
    IndexedPaletteEntry {
        key: 'w',
        colour: Some(Rgb::new(125, 118, 99)),
    },
    IndexedPaletteEntry {
        key: 'W',
        colour: Some(Rgb::new(219, 211, 183)),
    },
    IndexedPaletteEntry {
        key: 'd',
        colour: Some(Rgb::new(84, 51, 32)),
    },
    IndexedPaletteEntry {
        key: 'D',
        colour: Some(Rgb::new(158, 100, 53)),
    },
    IndexedPaletteEntry {
        key: 'm',
        colour: Some(Rgb::new(110, 86, 52)),
    },
    IndexedPaletteEntry {
        key: 'M',
        colour: Some(Rgb::new(191, 163, 104)),
    },
    IndexedPaletteEntry {
        key: 'l',
        colour: Some(Rgb::new(217, 179, 78)),
    },
    IndexedPaletteEntry {
        key: 'e',
        colour: Some(Rgb::new(105, 232, 150)),
    },
    IndexedPaletteEntry {
        key: 'a',
        colour: Some(Rgb::new(85, 174, 206)),
    },
    IndexedPaletteEntry {
        key: 'p',
        colour: Some(Rgb::new(200, 180, 137)),
    },
    IndexedPaletteEntry {
        key: 'P',
        colour: Some(Rgb::new(240, 223, 175)),
    },
    IndexedPaletteEntry {
        key: 's',
        colour: Some(Rgb::new(166, 78, 85)),
    },
];

const DRUID_WORKING_A: &[&str] = &[
    "...m.......m....",
    "...Mm.....mM....",
    "....m.ooo.m.....",
    "....ocCCCco.....",
    "...ocCCvCCco....",
    "..ocCCvvvCCco...",
    "..ocCKhhKKCco...",
    "..ocCKoKKoCco...",
    "..ocCKKKKKCco...",
    "..ocCKKhhKCco...",
    "...ocwWWWWco....",
    "....owWWWwo...D.",
    "...ocCCCCco..vD.",
    "...ocKCCCcKovvD.",
    "...ocKCCCCKooDD.",
    "...ocCClCCCco.D.",
    "....ocCllCCco.D.",
    "....ocCCCCCco.D.",
    "....olllllllo.D.",
    ".....oddddo...D.",
    "....oDd..dDo..D.",
    "....ooo..ooo....",
    "................",
    "................",
];

const DRUID_WORKING_B: &[&str] = &[
    "...m.......m....",
    "...Mm.....mM....",
    "....m.ooo.m.....",
    "....ocCCCco.....",
    "...ocCCvCCco....",
    "..ocCCvvvCCco...",
    "..ocCKhhKKCco...",
    "..ocCKoKKoCco...",
    "..ocCKKKKKCco...",
    "..ocCKKhhKCco...",
    "...ocwWWWWco....",
    "....owWWWwo...D.",
    "...ocCCCCco...D.",
    "...ocKCCCco.vvD.",
    "...ocKCCCcKKvDD.",
    "...ocCClCCCco.D.",
    "....ocCllCCco.D.",
    "....ocCCCCCco.D.",
    "....olllllllo.D.",
    ".....oddddo...D.",
    "....oDd..dDo..D.",
    "....ooo..ooo....",
    "................",
    "................",
];

const DRUID_COUNSEL_RAISE: &[&str] = &[
    "...m.......m....",
    "...Mm.....mM....",
    "....m.ooo.m.....",
    "....ocCCCco.....",
    "...ocCCvCCco....",
    "..ocCCvvvCCco...",
    "..ocCKhhKKCco...",
    "..ocCKoKKoCco...",
    "..ocCKKKKKCco...",
    "..ocCKKhhKCco...",
    ".KhocwWWWWco....",
    ".KK.owWWWwo...D.",
    "..oocCCCCco..vD.",
    "...ocCCCCcco.vD.",
    "...ocCCCCCKooDD.",
    "...ocKClCCCco.D.",
    "....ocCllCCco.D.",
    "....ocCCCCCco.D.",
    "....olllllllo.D.",
    ".....oddddo...D.",
    "....oDd..dDo..D.",
    "....ooo..ooo....",
    "................",
    "................",
];

const DRUID_COUNSEL_WAIT: &[&str] = &[
    "...m.......m....",
    "...Mm.....mM....",
    "....m.ooo.m.....",
    "....ocCCCco.....",
    "...ocCCvCCco....",
    "..ocCCvvvCCco...",
    "..ocCKhhKKCco...",
    "..ocCKoKKoCco...",
    "..ocCKKKKKCco...",
    "..ocCKKhhKCco...",
    "...ocwWWWWco....",
    "....owWWWwo...D.",
    "...ocCCCCco..vD.",
    "...ocCCCCcco.vD.",
    "...ocCCCCCKooDD.",
    "...ocKClCCCco.D.",
    "....ocCllCCco.D.",
    "....ocCCCCCco.D.",
    "....olllllllo.D.",
    ".....oddddo...D.",
    "....oDd..dDo..D.",
    "....ooo..ooo....",
    "................",
    "................",
];

const DRUID_SPOILS: &[&str] = &[
    "...m.......m....",
    "...Mm.....mM....",
    "....m.ooo.m.....",
    "....ocCCCco.....",
    "...ocCCvCCco....",
    "..ocCCvvvCCco...",
    "..ocCKhhKKCco...",
    "..ocCKoKKoCco...",
    "..ocCKKKKKCco...",
    "..ocCKKhhKCco...",
    "...ocwWWWWco....",
    "....owWWWwo...D.",
    "...ocCCCCco..vD.",
    "...ocCCCCcco.vD.",
    "...ocCCCCCKooDD.",
    ".oDDocClCCCco.D.",
    ".KDsKoCllCCco.D.",
    ".oDDocCCCCCco.D.",
    "....olllllllo.D.",
    ".....oddddo...D.",
    "....oDd..dDo..D.",
    "....ooo..ooo....",
    "................",
    "................",
];

const DRUID_RESTING: &[&str] = &[
    "...m.......m....",
    "...Mm.....mM....",
    "....m.ooo.m.....",
    "....ocCCCco.....",
    "...ocCCvCCco....",
    "..ocCCvvvCCco...",
    "..ocCKhhKKCco...",
    "..ocCKoKKoCco...",
    "..ocCKKKKKCco...",
    "..ocCKKhhKCco...",
    "...ocwWWWWco....",
    "....owWWWwo...D.",
    "...ocCCCCco..vD.",
    "...ocCCCCcco.vD.",
    "...ocCCCCCKooDD.",
    "...ocKClCCCco.D.",
    "....ocCllCCco.D.",
    "....ocCCCCCco.D.",
    "....olllllllo.D.",
    ".....oddddo...D.",
    "....oDd..dDo..D.",
    "....ooo..ooo....",
    "................",
    "................",
];

const DRUID_UNKNOWN: &[&str] = &[
    "...m.......m....",
    "...Mm.....mM....",
    "....m.ooo.m.....",
    "....ocCCCco.....",
    "...ocCCvCCco....",
    "..ocCCvvvCCco...",
    "..ocCKhhKKCco...",
    "..ocCKoKKKCco...",
    "..ocCKKKKoCco...",
    "..ocCKKhhKCco...",
    "...ocwWWWWco....",
    "....owWWWwo...D.",
    "...ocCCCCco..vD.",
    "...ocCCCCcco.vD.",
    "...ocCCCCCKooDD.",
    "...ocKClCCCco.D.",
    "....ocCllCCco.D.",
    "....ocCCCCCco.D.",
    "....olllllllo.D.",
    ".....oddddo...D.",
    "....oDd..dDo..D.",
    "....ooo..ooo....",
    "................",
    "................",
];

const DRUID_SETTLED: &[&str] = &[
    "...m.......m....",
    "...Mm.....mM....",
    "....m.ooo.m.....",
    "....ocCCCco.....",
    "...ocCCvCCco....",
    "..ocCCvvvCCco...",
    "..ocCKhhKKCco...",
    "..ocCKoKKoCco...",
    "..ocCKKKKKCco...",
    "..ocCKKhhKCco...",
    "...ocwWWWWco....",
    "....owWWWwo...D.",
    "...ocCCCCco..vD.",
    "...ocCCCCcco.vD.",
    "...ocCCCCCKooDD.",
    "...ocKClCCCco.D.",
    "....ocCllCCco.D.",
    "....ocCCCCCco.D.",
    "....olllllllo.D.",
    ".oDDooddddo...D.",
    ".oDsDDd..dDo..D.",
    "....ooo..ooo....",
    "................",
    "................",
];

pub(super) const DRUID: ClassArt = ClassArt {
    palette: DRUID_PALETTE,
    frames: [
        DRUID_WORKING_A,
        DRUID_WORKING_B,
        DRUID_COUNSEL_RAISE,
        DRUID_COUNSEL_WAIT,
        DRUID_SPOILS,
        DRUID_RESTING,
        DRUID_UNKNOWN,
        DRUID_SETTLED,
    ],
    roster: None,
};
