//! Approved 2026-09-08 tool ritual pixels. Keep palette roles and rows authored;
//! runtime sampling and persona substitution live in the existing asset paths.
use super::{ClassArt, IndexedPaletteEntry, Rgb};

const BARD_PALETTE: &[IndexedPaletteEntry] = &[
    IndexedPaletteEntry {
        key: 'o',
        colour: Some(Rgb::new(29, 20, 31)),
    },
    IndexedPaletteEntry {
        key: 'k',
        colour: Some(Rgb::new(133, 73, 48)),
    },
    IndexedPaletteEntry {
        key: 'K',
        colour: Some(Rgb::new(235, 157, 101)),
    },
    IndexedPaletteEntry {
        key: 'h',
        colour: Some(Rgb::new(255, 218, 155)),
    },
    IndexedPaletteEntry {
        key: 'r',
        colour: Some(Rgb::new(71, 38, 36)),
    },
    IndexedPaletteEntry {
        key: 'R',
        colour: Some(Rgb::new(119, 59, 46)),
    },
    IndexedPaletteEntry {
        key: 'c',
        colour: Some(Rgb::new(80, 39, 77)),
    },
    IndexedPaletteEntry {
        key: 'C',
        colour: Some(Rgb::new(147, 66, 126)),
    },
    IndexedPaletteEntry {
        key: 'v',
        colour: Some(Rgb::new(211, 96, 164)),
    },
    IndexedPaletteEntry {
        key: 'd',
        colour: Some(Rgb::new(94, 56, 34)),
    },
    IndexedPaletteEntry {
        key: 'D',
        colour: Some(Rgb::new(171, 111, 55)),
    },
    IndexedPaletteEntry {
        key: 'l',
        colour: Some(Rgb::new(237, 181, 77)),
    },
    IndexedPaletteEntry {
        key: 'L',
        colour: Some(Rgb::new(255, 221, 117)),
    },
    IndexedPaletteEntry {
        key: 'e',
        colour: Some(Rgb::new(117, 221, 233)),
    },
    IndexedPaletteEntry {
        key: 'p',
        colour: Some(Rgb::new(200, 180, 137)),
    },
    IndexedPaletteEntry {
        key: 'P',
        colour: Some(Rgb::new(240, 223, 175)),
    },
    IndexedPaletteEntry {
        key: 's',
        colour: Some(Rgb::new(166, 78, 85)),
    },
];

const BARD_WORKING_A: &[&str] = &[
    "................",
    "..........e.....",
    ".........ee.....",
    ".....oooeeo.....",
    "....ocCCClco....",
    "...oollllllloo..",
    "....orRRRRro....",
    "...orKhhKKKro...",
    "...orKoKKoKro...",
    "...orKKKKKKro...",
    "....orKKKKro..d.",
    "....ooRRRoo..dD.",
    "...ocCCCCcco.dD.",
    "...ocKCCCcKddD..",
    "...ocKKCDDDDDdo.",
    "...ocCCoDlDoDdo.",
    "....ocCoDLLDDdo.",
    "....ocCcoDDDdo..",
    "....ollllllooo..",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

const BARD_WORKING_B: &[&str] = &[
    "................",
    "..........e.....",
    ".........ee.....",
    ".....oooeeo.....",
    "....ocCCClco....",
    "...oollllllloo..",
    "....orRRRRro....",
    "...orKhhKKKro...",
    "...orKoKKoKro...",
    "...orKKKKKKro...",
    "....orKKKKro..d.",
    "....ooRRRoo..dD.",
    "...ocCCCCcco.dD.",
    "...ocKCCCcKddD..",
    "...ocKCCDDDDDdo.",
    "...ocCKoDlDoDdo.",
    "....ocKoDLLDDdo.",
    "....ocCcoDDDdo..",
    "....ollllllooo..",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

const BARD_COUNSEL_RAISE: &[&str] = &[
    "................",
    "..........e.....",
    ".........ee.....",
    ".....oooeeo.....",
    "....ocCCClco....",
    "...oollllllloo..",
    "....orRRRRro....",
    "...orKhhKKKro...",
    "...orKoKKoKro...",
    "...orKKKKKKro...",
    "....orKKKKro..d.",
    ".Kh.ooRRRoo..dD.",
    ".KKoocCCCCco.dD.",
    "..oocCCCCcKddD..",
    "....ocCCDDDDDdo.",
    "...ocCCoDlDoDdo.",
    "....ocCoDLLDDdo.",
    "....ocCcoDDDdo..",
    "....ollllllooo..",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

const BARD_COUNSEL_WAIT: &[&str] = &[
    "................",
    "..........e.....",
    ".........ee.....",
    ".....oooeeo.....",
    "....ocCCClco....",
    "...oollllllloo..",
    "....orRRRRro....",
    "...orKhhKKKro...",
    "...orKoKKoKro...",
    "...orKKKKKKro...",
    "....orKKKKro..d.",
    "....ooRRRoo..dD.",
    "...ocCCCCcco.dD.",
    "...ocCCCCcKddD..",
    "...ocCCCDDDDDdo.",
    "...ocCKoDlDoDdo.",
    "....ocKoDLLDDdo.",
    "....ocCcoDDDdo..",
    "....ollllllooo..",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

const BARD_SPOILS: &[&str] = &[
    "................",
    "..........e.....",
    ".........ee.....",
    ".....oooeeo.....",
    "....ocCCClco....",
    "...oollllllloo..",
    "....orRRRRro....",
    "...orKhhKKKro...",
    "...orKoKKoKro...",
    "...orKKKKKKro...",
    "....orKKKKro..d.",
    "....ooRRRoo..dD.",
    "...ocCCCCcco.dD.",
    "...ocCCCCcKddD..",
    "...ocCCCDDDDDdo.",
    "...ocCCoDlDoDdo.",
    ".oPPPooDLLDDdo..",
    ".KPsPKocoDDDdo..",
    ".oPPPoo.lllloo..",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

const BARD_RESTING: &[&str] = &[
    "................",
    "..........e.....",
    ".........ee.....",
    ".....oooeeo.....",
    "....ocCCClco....",
    "...oollllllloo..",
    "....orRRRRro....",
    "...orKhhKKKro...",
    "...orKoKKoKro...",
    "...orKKKKKKro...",
    "....orKKKKro..d.",
    "....ooRRRoo..dD.",
    "...ocCCCCcco.dD.",
    "...ocCCCCcKddD..",
    "...ocCCCDDDDDdo.",
    "...ocCCoDlDoDdo.",
    "....ocKoDLLDDdo.",
    "....ocCcoDDDdo..",
    "....ollllllooo..",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

const BARD_UNKNOWN: &[&str] = &[
    "................",
    "..........e.....",
    ".........ee.....",
    ".....oooeeo.....",
    "....ocCCClco....",
    "...oollllllloo..",
    "....orRRRRro....",
    "...orKhhKKKro...",
    "...orKoKKKKro...",
    "...orKKKKoKro...",
    "....orKKKKro..d.",
    "....ooRRRoo..dD.",
    "...ocCCCCcco.dD.",
    "...ocCCCCcKddD..",
    "...ocCCCDDDDDdo.",
    "...ocCCoDlDoDdo.",
    "....ocCoDLLDDdo.",
    "....ocCcoDDDdo..",
    "....ollllllooo..",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

const BARD_SETTLED: &[&str] = &[
    "................",
    "..........e.....",
    ".........ee.....",
    ".....oooeeo.....",
    "....ocCCClco....",
    "...oollllllloo..",
    "....orRRRRro....",
    "...orKhhKKKro...",
    "...orKoKKoKro...",
    "...orKKKKKKro...",
    "....orKKKKro..d.",
    "....ooRRRoo..dD.",
    "...ocCCCCcco.dD.",
    "...ocCCCCcKddD..",
    "...ocCCCDDDDDdo.",
    "...ocCCoDlDoDdo.",
    "....ocKoDLLDDdo.",
    "....ocCcoDDDdo..",
    "....ollllllooo..",
    ".oPPPooddddo....",
    ".oPsPoDd..dDo...",
    "....ooo..ooo....",
    "................",
    "................",
];

pub(super) const BARD: ClassArt = ClassArt {
    palette: BARD_PALETTE,
    frames: [
        BARD_WORKING_A,
        BARD_WORKING_B,
        BARD_COUNSEL_RAISE,
        BARD_COUNSEL_WAIT,
        BARD_SPOILS,
        BARD_RESTING,
        BARD_UNKNOWN,
        BARD_SETTLED,
    ],
    roster: None,
};

const ARTIFICER_PALETTE: &[IndexedPaletteEntry] = &[
    IndexedPaletteEntry {
        key: 'o',
        colour: Some(Rgb::new(24, 21, 30)),
    },
    IndexedPaletteEntry {
        key: 'k',
        colour: Some(Rgb::new(139, 82, 52)),
    },
    IndexedPaletteEntry {
        key: 'K',
        colour: Some(Rgb::new(232, 164, 103)),
    },
    IndexedPaletteEntry {
        key: 'h',
        colour: Some(Rgb::new(255, 224, 164)),
    },
    IndexedPaletteEntry {
        key: 'r',
        colour: Some(Rgb::new(48, 42, 58)),
    },
    IndexedPaletteEntry {
        key: 'R',
        colour: Some(Rgb::new(86, 76, 96)),
    },
    IndexedPaletteEntry {
        key: 'c',
        colour: Some(Rgb::new(46, 42, 88)),
    },
    IndexedPaletteEntry {
        key: 'C',
        colour: Some(Rgb::new(88, 80, 146)),
    },
    IndexedPaletteEntry {
        key: 'l',
        colour: Some(Rgb::new(198, 152, 72)),
    },
    IndexedPaletteEntry {
        key: 'm',
        colour: Some(Rgb::new(112, 120, 128)),
    },
    IndexedPaletteEntry {
        key: 'M',
        colour: Some(Rgb::new(206, 214, 214)),
    },
    IndexedPaletteEntry {
        key: 'd',
        colour: Some(Rgb::new(92, 55, 34)),
    },
    IndexedPaletteEntry {
        key: 'D',
        colour: Some(Rgb::new(157, 93, 45)),
    },
    IndexedPaletteEntry {
        key: 'a',
        colour: Some(Rgb::new(227, 150, 47)),
    },
    IndexedPaletteEntry {
        key: 'e',
        colour: Some(Rgb::new(255, 196, 84)),
    },
    IndexedPaletteEntry {
        key: 'p',
        colour: Some(Rgb::new(200, 180, 137)),
    },
    IndexedPaletteEntry {
        key: 'P',
        colour: Some(Rgb::new(240, 223, 175)),
    },
    IndexedPaletteEntry {
        key: 's',
        colour: Some(Rgb::new(166, 78, 85)),
    },
];

const ARTIFICER_WORKING_A: &[&str] = &[
    "................",
    "......oooo......",
    ".....orRRRro....",
    "....orRRRRRro...",
    "...orRMMMMMRro..",
    "...orMeMMeMMro..",
    "....okKKKKko....",
    "...okKhhKKKko...",
    "...okKoKKoKko...",
    "...okKKKKKKko...",
    "....okKhhKko....",
    ".....oooooo.....",
    ".m.m.ocCCCCco...",
    ".mMmocKCClCCco..",
    "..m.ocKCCodDdo..",
    "..m.ocClKDeDlKo.",
    "..m..ocCoDMDDo..",
    ".....ocCCodDoo..",
    ".....ollllllo...",
    "......oddddo....",
    ".....oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const ARTIFICER_WORKING_B: &[&str] = &[
    "................",
    "......oooo......",
    ".....orRRRro....",
    "....orRRRRRro...",
    "...orRMMMMMRro..",
    "...orMeMMeMMro..",
    "....okKKKKko....",
    "...okKhhKKKko...",
    "...okKoKKoKko...",
    "...okKKKKKKko...",
    "....okKhhKko....",
    ".....oooooo.....",
    ".m.m.ocCCCCco...",
    ".mMmocCCClCCco..",
    "..m.ocCCCoDKdo..",
    "..m.ocClKDeDlKo.",
    "..m..ocCoDMMDo..",
    ".....ocCCodDoo..",
    ".....ollllllo...",
    "......oddddo....",
    ".....oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const ARTIFICER_COUNSEL_RAISE: &[&str] = &[
    "................",
    "......oooo......",
    ".....orRRRro....",
    "....orRRRRRro...",
    "...orRMMMMMRro..",
    "...orMeMMeMMro..",
    "....okKKKKko....",
    "...okKhhKKKko...",
    "...okKoKKoKko...",
    "...okKKKKKKko...",
    "....okKhhKko....",
    ".Kh..oooooo.....",
    ".KKoocCCCCco....",
    "..oocCCCClCCco..",
    "..m.ocKCCodDdo..",
    "..m.ocClKDeDlKo.",
    "..m..ocCoDMDDo..",
    ".....ocCCodDoo..",
    ".....ollllllo...",
    "......oddddo....",
    ".....oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const ARTIFICER_COUNSEL_WAIT: &[&str] = &[
    "................",
    "......oooo......",
    ".....orRRRro....",
    "....orRRRRRro...",
    "...orRMMMMMRro..",
    "...orMeMMeMMro..",
    "....okKKKKko....",
    "...okKhhKKKko...",
    "...okKoKKoKko...",
    "...okKKKKKKko...",
    "....okKhhKko....",
    ".....oooooo.....",
    ".m.m.ocCCCCco...",
    ".mMmocCCClCCco..",
    "..m.ocCCCodDdo..",
    "..m.ocClKDeDlKo.",
    "..m..ocCoDMDDo..",
    ".....ocCCodDoo..",
    ".....ollllllo...",
    "......oddddo....",
    ".....oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const ARTIFICER_SPOILS: &[&str] = &[
    "................",
    "......oooo......",
    ".....orRRRro....",
    "....orRRRRRro...",
    "...orRMMMMMRro..",
    "...orMeMMeMMro..",
    "....okKKKKko....",
    "...okKhhKKKko...",
    "...okKoKKoKko...",
    "...okKKKKKKko...",
    "....okKhhKko....",
    ".....oooooo.....",
    ".m.m.ocCCCCco...",
    ".mMmocCCClCCco..",
    "..m.ocCCCoDDDdo.",
    "..m.ocClKDsssKo.",
    "..m..ocCoDDDDDo.",
    ".....ocCCoDDoo..",
    ".....ollllllo...",
    "......oddddo....",
    ".....oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const ARTIFICER_RESTING: &[&str] = &[
    "................",
    "......oooo......",
    ".....orRRRro....",
    "....orRRRRRro...",
    "...orRMMMMMRro..",
    "...orMeMMeMMro..",
    "....okKKKKko....",
    "...okKhhKKKko...",
    "...okKoKKoKko...",
    "...okKKKKKKko...",
    "....okKhhKko....",
    ".....oooooo.....",
    ".m.m.ocCCCCco...",
    ".mMmocCCClCCco..",
    "..m.ocCCCodDdo..",
    "..m.ocClKDeDlKo.",
    "..m..ocCoDMDDo..",
    ".....ocCCodDoo..",
    ".....ollllllo...",
    "......oddddo....",
    ".....oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const ARTIFICER_UNKNOWN: &[&str] = &[
    "................",
    "......oooo......",
    ".....orRRRro....",
    "....orRRRRRro...",
    "...orRMMMMMRro..",
    "...orMeMMeMMro..",
    "....okKKKKko....",
    "...okKhhKKKko...",
    "...okKoKKKKko...",
    "...okKKKKoKko...",
    "....okKhhKko....",
    ".....oooooo.....",
    ".m.m.ocCCCCco...",
    ".mMmocCCClCCco..",
    "..m.ocCCCodDdo..",
    "..m.ocClKDeDlKo.",
    "..m..ocCoDMDDo..",
    ".....ocCCodDoo..",
    ".....ollllllo...",
    "......oddddo....",
    ".....oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const ARTIFICER_SETTLED: &[&str] = &[
    "................",
    "......oooo......",
    ".....orRRRro....",
    "....orRRRRRro...",
    "...orRMMMMMRro..",
    "...orMeMMeMMro..",
    "....okKKKKko....",
    "...okKhhKKKko...",
    "...okKoKKoKko...",
    "...okKKKKKKko...",
    "....okKhhKko....",
    ".....oooooo.....",
    ".m.m.ocCCCCco...",
    ".mMmocCCClCCco..",
    "..m.ocCCCCCCCco.",
    "..m.ocClKCCClKo.",
    "..m..ocCCCCCCo..",
    ".....ocCCCCCo...",
    ".....ollllllo...",
    ".oDDDo.ddddo....",
    ".oDsDoDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

pub(super) const ARTIFICER: ClassArt = ClassArt {
    palette: ARTIFICER_PALETTE,
    frames: [
        ARTIFICER_WORKING_A,
        ARTIFICER_WORKING_B,
        ARTIFICER_COUNSEL_RAISE,
        ARTIFICER_COUNSEL_WAIT,
        ARTIFICER_SPOILS,
        ARTIFICER_RESTING,
        ARTIFICER_UNKNOWN,
        ARTIFICER_SETTLED,
    ],
    roster: None,
};

const TESTMENDER_PALETTE: &[IndexedPaletteEntry] = &[
    IndexedPaletteEntry {
        key: 'o',
        colour: Some(Rgb::new(28, 24, 26)),
    },
    IndexedPaletteEntry {
        key: 'k',
        colour: Some(Rgb::new(142, 86, 56)),
    },
    IndexedPaletteEntry {
        key: 'K',
        colour: Some(Rgb::new(230, 160, 102)),
    },
    IndexedPaletteEntry {
        key: 'h',
        colour: Some(Rgb::new(255, 220, 158)),
    },
    IndexedPaletteEntry {
        key: 'w',
        colour: Some(Rgb::new(172, 160, 136)),
    },
    IndexedPaletteEntry {
        key: 'W',
        colour: Some(Rgb::new(240, 232, 208)),
    },
    IndexedPaletteEntry {
        key: 'c',
        colour: Some(Rgb::new(120, 104, 78)),
    },
    IndexedPaletteEntry {
        key: 'C',
        colour: Some(Rgb::new(198, 182, 146)),
    },
    IndexedPaletteEntry {
        key: 'l',
        colour: Some(Rgb::new(236, 216, 168)),
    },
    IndexedPaletteEntry {
        key: 'm',
        colour: Some(Rgb::new(126, 134, 140)),
    },
    IndexedPaletteEntry {
        key: 'M',
        colour: Some(Rgb::new(214, 222, 222)),
    },
    IndexedPaletteEntry {
        key: 'd',
        colour: Some(Rgb::new(88, 52, 40)),
    },
    IndexedPaletteEntry {
        key: 'D',
        colour: Some(Rgb::new(152, 88, 60)),
    },
    IndexedPaletteEntry {
        key: 'a',
        colour: Some(Rgb::new(158, 52, 62)),
    },
    IndexedPaletteEntry {
        key: 'e',
        colour: Some(Rgb::new(120, 206, 148)),
    },
    IndexedPaletteEntry {
        key: 'p',
        colour: Some(Rgb::new(200, 180, 137)),
    },
    IndexedPaletteEntry {
        key: 'P',
        colour: Some(Rgb::new(240, 223, 175)),
    },
    IndexedPaletteEntry {
        key: 's',
        colour: Some(Rgb::new(166, 78, 85)),
    },
];

const TESTMENDER_WORKING_A: &[&str] = &[
    "................",
    "......oooo......",
    "....oowWWWoo....",
    "...owWWWWWWwo...",
    "...owWWaaWWwo...",
    "...owWWWWWWwo...",
    "...owKKhhKKwo...",
    "...owKoKKoKwo...",
    "...owKKKKKKwo...",
    "...owKKhKKKwo...",
    "....owKKKKwo....",
    ".....oooooo.....",
    "....ocCCCCco....",
    "...ocKCCCClco.M.",
    "...ocKCCCCKcoM..",
    "...ocCoPPPoKM...",
    "...occKPsaPco...",
    "....ocoPPPPco...",
    "....olllllllo...",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

const TESTMENDER_WORKING_B: &[&str] = &[
    "................",
    "......oooo......",
    "....oowWWWoo....",
    "...owWWWWWWwo...",
    "...owWWaaWWwo...",
    "...owWWWWWWwo...",
    "...owKKhhKKwo...",
    "...owKoKKoKwo...",
    "...owKKKKKKwo...",
    "...owKKhKKKwo...",
    "....owKKKKwo....",
    ".....oooooo.....",
    "....ocCCCCco....",
    "...ocKCCCClco...",
    "...ocKCCCCcKo...",
    "...ocCoPPPMKo...",
    "...occKPsaPco...",
    "....ocoPPPPco...",
    "....olllllllo...",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

const TESTMENDER_COUNSEL_RAISE: &[&str] = &[
    "................",
    "......oooo......",
    "....oowWWWoo....",
    "...owWWWWWWwo...",
    "...owWWaaWWwo...",
    "...owWWWWWWwo...",
    "...owKKhhKKwo...",
    "...owKoKKoKwo...",
    "...owKKKKKKwo...",
    "...owKKhKKKwo...",
    "....owKKKKwo....",
    ".Kh..oooooo.....",
    ".KKoocCCCCco....",
    "..oocCCCCClco...",
    "...ocCCCCCCco...",
    "...ocCoPPPoKo...",
    "...occKPsaPco...",
    "....ocoPPPPco...",
    "....olllllllo...",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

const TESTMENDER_COUNSEL_WAIT: &[&str] = &[
    "................",
    "......oooo......",
    "....oowWWWoo....",
    "...owWWWWWWwo...",
    "...owWWaaWWwo...",
    "...owWWWWWWwo...",
    "...owKKhhKKwo...",
    "...owKoKKoKwo...",
    "...owKKKKKKwo...",
    "...owKKhKKKwo...",
    "....owKKKKwo....",
    ".....oooooo.....",
    "....ocCCCCco....",
    "...ocCCCCClco...",
    "...ocCCCCCCco...",
    "...ocCoPPPoKo...",
    "...occKPsaPco...",
    "....ocoPPPPco...",
    "....olllllllo...",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

const TESTMENDER_SPOILS: &[&str] = &[
    "................",
    "......oooo......",
    "....oowWWWoo....",
    "...owWWWWWWwo...",
    "...owWWaaWWwo...",
    "...owWWWWWWwo...",
    "...owKKhhKKwo...",
    "...owKoKKoKwo...",
    "...owKKKKKKwo...",
    "...owKKhKKKwo...",
    "....owKKKKwo....",
    ".....oooooo.....",
    "....ocCCCCco....",
    "...ocCCCCClco...",
    "...ocCCCCCCco...",
    "...ocKoPPPoo....",
    "...ocKoPsPKco...",
    "....ocoPPPoCo...",
    "....olllllllo...",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

const TESTMENDER_RESTING: &[&str] = &[
    "................",
    "......oooo......",
    "....oowWWWoo....",
    "...owWWWWWWwo...",
    "...owWWaaWWwo...",
    "...owWWWWWWwo...",
    "...owKKhhKKwo...",
    "...owKoKKoKwo...",
    "...owKKKKKKwo...",
    "...owKKhKKKwo...",
    "....owKKKKwo....",
    ".....oooooo.....",
    "....ocCCCCco....",
    "...ocCCCCClco...",
    "...ocCCCCCCco...",
    "...ocCoPPPoKo...",
    "...occKPsaPco...",
    "....ocoPPPPco...",
    "....olllllllo...",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

const TESTMENDER_UNKNOWN: &[&str] = &[
    "................",
    "......oooo......",
    "....oowWWWoo....",
    "...owWWWWWWwo...",
    "...owWWaaWWwo...",
    "...owWWWWWWwo...",
    "...owKKhhKKwo...",
    "...owKoKKKKwo...",
    "...owKKKKoKwo...",
    "...owKKhKKKwo...",
    "....owKKKKwo....",
    ".....oooooo.....",
    "....ocCCCCco....",
    "...ocCCCCClco...",
    "...ocCCCCCCco...",
    "...ocCoPPPoKo...",
    "...occKPsaPco...",
    "....ocoPPPPco...",
    "....olllllllo...",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

const TESTMENDER_SETTLED: &[&str] = &[
    "................",
    "......oooo......",
    "....oowWWWoo....",
    "...owWWWWWWwo...",
    "...owWWaaWWwo...",
    "...owWWWWWWwo...",
    "...owKKhhKKwo...",
    "...owKoKKoKwo...",
    "...owKKKKKKwo...",
    "...owKKhKKKwo...",
    "....owKKKKwo....",
    ".....oooooo.....",
    "....ocCCCCco....",
    "...ocCCCCClco...",
    "...ocCCCCCCco...",
    "...ocKCCCClKo...",
    "...ocCCCCCCCco..",
    "....ocCCCCCco...",
    "....olllllllo...",
    ".oPPPooddddo....",
    ".oPsPoDd..dDo...",
    "....ooo..ooo....",
    "................",
    "................",
];

pub(super) const TESTMENDER: ClassArt = ClassArt {
    palette: TESTMENDER_PALETTE,
    frames: [
        TESTMENDER_WORKING_A,
        TESTMENDER_WORKING_B,
        TESTMENDER_COUNSEL_RAISE,
        TESTMENDER_COUNSEL_WAIT,
        TESTMENDER_SPOILS,
        TESTMENDER_RESTING,
        TESTMENDER_UNKNOWN,
        TESTMENDER_SETTLED,
    ],
    roster: None,
};
