//! Approved 2026-09-08 Rogue, Pathseeker and Runewright ritual pixels.
//! Runtime sampling and persona substitution use the existing asset paths.
use super::{ClassArt, IndexedPaletteEntry, Rgb};

const ROGUE_PALETTE: &[IndexedPaletteEntry] = &[
    IndexedPaletteEntry {
        key: 'o',
        colour: Some(Rgb::new(21, 18, 29)),
    },
    IndexedPaletteEntry {
        key: 'k',
        colour: Some(Rgb::new(125, 72, 47)),
    },
    IndexedPaletteEntry {
        key: 'K',
        colour: Some(Rgb::new(225, 151, 97)),
    },
    IndexedPaletteEntry {
        key: 'h',
        colour: Some(Rgb::new(255, 218, 151)),
    },
    IndexedPaletteEntry {
        key: 'r',
        colour: Some(Rgb::new(49, 30, 63)),
    },
    IndexedPaletteEntry {
        key: 'R',
        colour: Some(Rgb::new(82, 51, 110)),
    },
    IndexedPaletteEntry {
        key: 'c',
        colour: Some(Rgb::new(52, 38, 78)),
    },
    IndexedPaletteEntry {
        key: 'C',
        colour: Some(Rgb::new(98, 65, 137)),
    },
    IndexedPaletteEntry {
        key: 'v',
        colour: Some(Rgb::new(157, 111, 204)),
    },
    IndexedPaletteEntry {
        key: 'd',
        colour: Some(Rgb::new(86, 54, 35)),
    },
    IndexedPaletteEntry {
        key: 'D',
        colour: Some(Rgb::new(155, 100, 55)),
    },
    IndexedPaletteEntry {
        key: 'l',
        colour: Some(Rgb::new(219, 184, 87)),
    },
    IndexedPaletteEntry {
        key: 'a',
        colour: Some(Rgb::new(70, 190, 181)),
    },
    IndexedPaletteEntry {
        key: 'm',
        colour: Some(Rgb::new(130, 146, 151)),
    },
    IndexedPaletteEntry {
        key: 'M',
        colour: Some(Rgb::new(223, 232, 224)),
    },
    IndexedPaletteEntry {
        key: 'e',
        colour: Some(Rgb::new(91, 228, 223)),
    },
    IndexedPaletteEntry {
        key: 'p',
        colour: Some(Rgb::new(200, 180, 137)),
    },
    IndexedPaletteEntry {
        key: 'P',
        colour: Some(Rgb::new(240, 223, 175)),
    },
    IndexedPaletteEntry {
        key: 's',
        colour: Some(Rgb::new(166, 78, 85)),
    },
];

const ROGUE_WORKING_A: &[&str] = &[
    "................",
    "........oo......",
    "......ooccCo....",
    ".....ocCCCCco...",
    "....ocCCvCCCco..",
    "...ocCCvvCCCco..",
    "...ocKhhKKKKco..",
    "...ocKoKKoKKco..",
    "...occccccccCo..",
    "...ocCCCCCCCco..",
    "....ocCCCCCCo...",
    ".....ooooooo....",
    "....ocCCCCco....",
    "...ocKCCCCcKo...",
    "...ocKKlMMllco..",
    "...ocCColDloKo..",
    "...ocCCoDDoMco..",
    "..moocColDloooM.",
    "..d..ollllllo.d.",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

const ROGUE_WORKING_B: &[&str] = &[
    "................",
    "........oo......",
    "......ooccCo....",
    ".....ocCCCCco...",
    "....ocCCvCCCco..",
    "...ocCCvvCCCco..",
    "...ocKhhKKKKco..",
    "...ocKoKKoKKco..",
    "...occccccccCo..",
    "...ocCCCCCCCco..",
    "....ocCCCCCCo...",
    ".....ooooooo....",
    "....ocCCCCco....",
    "...ocKCCCCcKo...",
    "...ocKCollllco..",
    "...ocKKolDloKo..",
    "...ocCCoDDMMco..",
    "..moocColDloooM.",
    "..d..ollllllo.d.",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

const ROGUE_COUNSEL_RAISE: &[&str] = &[
    "................",
    "........oo......",
    "......ooccCo....",
    ".....ocCCCCco...",
    "....ocCCvCCCco..",
    "...ocCCvvCCCco..",
    "...ocKhhKKKKco..",
    "...ocKoKKoKKco..",
    "...occccccccCo..",
    "...ocCCCCCCCco..",
    ".Kh.ocCCCCCCo...",
    ".KK..ooooooo....",
    "..ooocCCCCco....",
    "...ocCCCCCCco...",
    "...ocCCollllco..",
    "...ocKColDloKo..",
    "...ocCCoDDoMco..",
    "..moocColDloooM.",
    "..d..ollllllo.d.",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

const ROGUE_COUNSEL_WAIT: &[&str] = &[
    "................",
    "........oo......",
    "......ooccCo....",
    ".....ocCCCCco...",
    "....ocCCvCCCco..",
    "...ocCCvvCCCco..",
    "...ocKhhKKKKco..",
    "...ocKoKKoKKco..",
    "...occccccccCo..",
    "...ocCCCCCCCco..",
    "....ocCCCCCCo...",
    ".....ooooooo....",
    "....ocCCCCco....",
    "...ocCCCCCCco...",
    "...ocCCollllco..",
    "...ocKColDloKo..",
    "...ocCCoDDoMco..",
    "..moocColDloooM.",
    "..d..ollllllo.d.",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

const ROGUE_SPOILS: &[&str] = &[
    "................",
    "........oo......",
    "......ooccCo....",
    ".....ocCCCCco...",
    "....ocCCvCCCco..",
    "...ocCCvvCCCco..",
    "...ocKhhKKKKco..",
    "...ocKoKKoKKco..",
    "...occccccccCo..",
    "...ocCCCCCCCco..",
    "....ocCCCCCCo...",
    ".....ooooooo....",
    "....ocCCCCco....",
    "...ocCCCCCCco...",
    "...ocCCoPPPoCo..",
    "...ocKCoPsPoKo..",
    "...ocCCoPPPoCo..",
    "..moocColDloooM.",
    "..d..ollllllo.d.",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

const ROGUE_RESTING: &[&str] = &[
    "................",
    "........oo......",
    "......ooccCo....",
    ".....ocCCCCco...",
    "....ocCCvCCCco..",
    "...ocCCvvCCCco..",
    "...ocKhhKKKKco..",
    "...ocKoKKoKKco..",
    "...occccccccCo..",
    "...ocCCCCCCCco..",
    "....ocCCCCCCo...",
    ".....ooooooo....",
    "....ocCCCCco....",
    "...ocCCCCCCco...",
    "...ocCCollllco..",
    "...ocKColDloKo..",
    "...ocCCoDDoMco..",
    "..moocColDloooM.",
    "..d..ollllllo.d.",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

const ROGUE_UNKNOWN: &[&str] = &[
    "................",
    "........oo......",
    "......ooccCo....",
    ".....ocCCCCco...",
    "....ocCCvCCCco..",
    "...ocCCvvCCCco..",
    "...ocKhhKKKKco..",
    "...ocKoKKKKKco..",
    "...occccccccCo..",
    "...ocCCCCCCCco..",
    "....ocCCCCCCo...",
    ".....ooooooo....",
    "....ocCCCCco....",
    "...ocCCCCCCco...",
    "...ocCCollllco..",
    "...ocKColDloKo..",
    "...ocCCoDDoMco..",
    "..moocColDloooM.",
    "..d..ollllllo.d.",
    ".....oddddo.....",
    "....oDd..dDo....",
    "....ooo..ooo....",
    "................",
    "................",
];

const ROGUE_SETTLED: &[&str] = &[
    "................",
    "........oo......",
    "......ooccCo....",
    ".....ocCCCCco...",
    "....ocCCvCCCco..",
    "...ocCCvvCCCco..",
    "...ocKhhKKKKco..",
    "...ocKoKKoKKco..",
    "...occccccccCo..",
    "...ocCCCCCCCco..",
    "....ocCCCCCCo...",
    ".....ooooooo....",
    "....ocCCCCco....",
    "...ocCCCCCCco...",
    "...ocCCCCCCCco..",
    "...ocKCCCCCKco..",
    "...ocCCCCCCCco..",
    "..moocCCCCCCooM.",
    "..d..ollllllo.d.",
    ".oPPPooddddo....",
    ".oPsPoDd..dDo...",
    "....ooo..ooo....",
    "................",
    "................",
];

pub(super) const ROGUE: ClassArt = ClassArt {
    palette: ROGUE_PALETTE,
    frames: [
        ROGUE_WORKING_A,
        ROGUE_WORKING_B,
        ROGUE_COUNSEL_RAISE,
        ROGUE_COUNSEL_WAIT,
        ROGUE_SPOILS,
        ROGUE_RESTING,
        ROGUE_UNKNOWN,
        ROGUE_SETTLED,
    ],
    roster: None,
};

const PATHSEEKER_PALETTE: &[IndexedPaletteEntry] = &[
    IndexedPaletteEntry {
        key: 'o',
        colour: Some(Rgb::new(22, 22, 20)),
    },
    IndexedPaletteEntry {
        key: 'k',
        colour: Some(Rgb::new(134, 84, 54)),
    },
    IndexedPaletteEntry {
        key: 'K',
        colour: Some(Rgb::new(228, 158, 100)),
    },
    IndexedPaletteEntry {
        key: 'h',
        colour: Some(Rgb::new(255, 218, 156)),
    },
    IndexedPaletteEntry {
        key: 'c',
        colour: Some(Rgb::new(58, 48, 36)),
    },
    IndexedPaletteEntry {
        key: 'C',
        colour: Some(Rgb::new(104, 88, 62)),
    },
    IndexedPaletteEntry {
        key: 'v',
        colour: Some(Rgb::new(74, 110, 72)),
    },
    IndexedPaletteEntry {
        key: 'l',
        colour: Some(Rgb::new(206, 180, 110)),
    },
    IndexedPaletteEntry {
        key: 'm',
        colour: Some(Rgb::new(120, 126, 118)),
    },
    IndexedPaletteEntry {
        key: 'M',
        colour: Some(Rgb::new(206, 212, 200)),
    },
    IndexedPaletteEntry {
        key: 'd',
        colour: Some(Rgb::new(84, 56, 34)),
    },
    IndexedPaletteEntry {
        key: 'D',
        colour: Some(Rgb::new(148, 98, 52)),
    },
    IndexedPaletteEntry {
        key: 'a',
        colour: Some(Rgb::new(137, 188, 73)),
    },
    IndexedPaletteEntry {
        key: 'e',
        colour: Some(Rgb::new(126, 232, 150)),
    },
    IndexedPaletteEntry {
        key: 'E',
        colour: Some(Rgb::new(214, 255, 214)),
    },
    IndexedPaletteEntry {
        key: 'p',
        colour: Some(Rgb::new(200, 180, 137)),
    },
    IndexedPaletteEntry {
        key: 'P',
        colour: Some(Rgb::new(240, 223, 175)),
    },
    IndexedPaletteEntry {
        key: 's',
        colour: Some(Rgb::new(166, 78, 85)),
    },
    IndexedPaletteEntry {
        key: 'L',
        colour: Some(Rgb::new(245, 223, 154)),
    },
];

const PATHSEEKER_WORKING_A: &[&str] = &[
    "..ddd...........",
    ".d...d..........",
    ".d...d.ooooo....",
    ".d...docCCCCo...",
    "..ddd.ocCvvCco..",
    "..d..ocCvvvCCco.",
    "..d..ocKhhKKKco.",
    "..d..ocKoKKoKco.",
    ".oeo.ocKKKKKKco.",
    "oeEeoocKKhhKKco.",
    ".oeo..ocvvvCCo..",
    "..d....ocCCoo...",
    "..d..ocCCCCco...",
    "..d..ocKCCCKco..",
    "..d..ocKollCo...",
    "..d..ocKleLlKo..",
    "..d..ocCoMloCo..",
    "..d...ocCCCCCco.",
    "..d...ollllllo..",
    "..d....oddddo...",
    "..d...oDd..dDo..",
    "......ooo..ooo..",
    "................",
    "................",
];

const PATHSEEKER_WORKING_B: &[&str] = &[
    "..ddd...........",
    ".d...d..........",
    ".d...d.ooooo....",
    ".d...docCCCCo...",
    "..ddd.ocCvvCco..",
    "..d..ocCvvvCCco.",
    "..d..ocKhhKKKco.",
    "..d..ocKoKKoKco.",
    ".oeo.ocKKKKKKco.",
    "oeEeoocKKhhKKco.",
    ".oeo..ocvvvCCo..",
    "..d....ocCCoo...",
    "..d..ocCCCCco...",
    "..d..ocKCCCKco..",
    "..d..ocColKCo...",
    "..d..ocKleeLKo..",
    "..d..ocCoLMoCo..",
    "..d...ocCCCCCco.",
    "..d...ollllllo..",
    "..d....oddddo...",
    "..d...oDd..dDo..",
    "......ooo..ooo..",
    "................",
    "................",
];

const PATHSEEKER_COUNSEL_RAISE: &[&str] = &[
    "..ddd...........",
    ".d...d..........",
    ".d...d.ooooo....",
    ".d...docCCCCo...",
    "..ddd.ocCvvCco..",
    "..d..ocCvvvCCco.",
    "..d..ocKhhKKKco.",
    "..d..ocKoKKoKco.",
    ".oeo.ocKKKKKKco.",
    "oeEeoocKKhhKKco.",
    ".Kh...ocvvvCCo..",
    ".KK....ocCCoo...",
    "..ooocCCCCco....",
    "..d..ocCCCCCCco.",
    "..d..ocColllo...",
    "..d..ocKleLlKo..",
    "..d..ocCoMloCo..",
    "..d...ocCCCCCco.",
    "..d...ollllllo..",
    "..d....oddddo...",
    "..d...oDd..dDo..",
    "......ooo..ooo..",
    "................",
    "................",
];

const PATHSEEKER_COUNSEL_WAIT: &[&str] = &[
    "..ddd...........",
    ".d...d..........",
    ".d...d.ooooo....",
    ".d...docCCCCo...",
    "..ddd.ocCvvCco..",
    "..d..ocCvvvCCco.",
    "..d..ocKhhKKKco.",
    "..d..ocKoKKoKco.",
    ".oeo.ocKKKKKKco.",
    "oeEeoocKKhhKKco.",
    ".oeo..ocvvvCCo..",
    "..d....ocCCoo...",
    "..d..ocCCCCco...",
    "..d..ocCCCCCCco.",
    "..d..ocColllo...",
    "..d..ocKleLlKo..",
    "..d..ocCoMloCo..",
    "..d...ocCCCCCco.",
    "..d...ollllllo..",
    "..d....oddddo...",
    "..d...oDd..dDo..",
    "......ooo..ooo..",
    "................",
    "................",
];

const PATHSEEKER_SPOILS: &[&str] = &[
    "..ddd...........",
    ".d...d..........",
    ".d...d.ooooo....",
    ".d...docCCCCo...",
    "..ddd.ocCvvCco..",
    "..d..ocCvvvCCco.",
    "..d..ocKhhKKKco.",
    "..d..ocKoKKoKco.",
    ".oeo.ocKKKKKKco.",
    "oeEeoocKKhhKKco.",
    ".oeo..ocvvvCCo..",
    "..d....ocCCoo...",
    "..d..ocCCCCco...",
    "..d..ocCCCCCCco.",
    "..d..ocCoPPPo...",
    "..d..ocKPPsPKo..",
    "..d..ocCoPPPoCo.",
    "..d...ocCCCCCco.",
    "..d...ollllllo..",
    "..d....oddddo...",
    "..d...oDd..dDo..",
    "......ooo..ooo..",
    "................",
    "................",
];

const PATHSEEKER_RESTING: &[&str] = &[
    "..ddd...........",
    ".d...d..........",
    ".d...d.ooooo....",
    ".d...docCCCCo...",
    "..ddd.ocCvvCco..",
    "..d..ocCvvvCCco.",
    "..d..ocKhhKKKco.",
    "..d..ocKoKKoKco.",
    ".oeo.ocKKKKKKco.",
    "oeEeoocKKhhKKco.",
    ".oeo..ocvvvCCo..",
    "..d....ocCCoo...",
    "..d..ocCCCCco...",
    "..d..ocCCCCCCco.",
    "..d..ocColllo...",
    "..d..ocKleLlKo..",
    "..d..ocCoMloCo..",
    "..d...ocCCCCCco.",
    "..d...ollllllo..",
    "..d....oddddo...",
    "..d...oDd..dDo..",
    "......ooo..ooo..",
    "................",
    "................",
];

const PATHSEEKER_UNKNOWN: &[&str] = &[
    "..ddd...........",
    ".d...d..........",
    ".d...d.ooooo....",
    ".d...docCCCCo...",
    "..ddd.ocCvvCco..",
    "..d..ocCvvvCCco.",
    "..d..ocKhhKKKco.",
    "..d..ocKoKKKKco.",
    "..d..ocKKKKoKco.",
    "oeEeoocKKhhKKco.",
    ".oeo..ocvvvCCo..",
    "..d....ocCCoo...",
    "..d..ocCCCCco...",
    "..d..ocCCCCCCco.",
    "..d..ocColllo...",
    "..d..ocKleLlKo..",
    "..d..ocCoMloCo..",
    "..d...ocCCCCCco.",
    "..d...ollllllo..",
    "..d....oddddo...",
    "..d...oDd..dDo..",
    "......ooo..ooo..",
    "................",
    "................",
];

const PATHSEEKER_SETTLED: &[&str] = &[
    "..ddd...........",
    ".d...d..........",
    ".d...d.ooooo....",
    ".d...docCCCCo...",
    "..ddd.ocCvvCco..",
    "..d..ocCvvvCCco.",
    "..d..ocKhhKKKco.",
    "..d..ocKoKKoKco.",
    ".oeo.ocKKKKKKco.",
    "oeEeoocKKhhKKco.",
    ".oeo..ocvvvCCo..",
    "..d....ocCCoo...",
    "..d..ocCCCCco...",
    "..d..ocCCCCCCco.",
    "..d..ocCCClCCco.",
    "..d..ocKCCCCKo..",
    "..d..ocCCeCCCco.",
    "..d...ocCCCCCco.",
    "..d...ollllllo..",
    "..d.PPooddddo...",
    "..d.PsPDd..dDo..",
    "......ooo..ooo..",
    "................",
    "................",
];

pub(super) const PATHSEEKER: ClassArt = ClassArt {
    palette: PATHSEEKER_PALETTE,
    frames: [
        PATHSEEKER_WORKING_A,
        PATHSEEKER_WORKING_B,
        PATHSEEKER_COUNSEL_RAISE,
        PATHSEEKER_COUNSEL_WAIT,
        PATHSEEKER_SPOILS,
        PATHSEEKER_RESTING,
        PATHSEEKER_UNKNOWN,
        PATHSEEKER_SETTLED,
    ],
    roster: None,
};

const RUNEWRIGHT_PALETTE: &[IndexedPaletteEntry] = &[
    IndexedPaletteEntry {
        key: 'o',
        colour: Some(Rgb::new(20, 26, 24)),
    },
    IndexedPaletteEntry {
        key: 'k',
        colour: Some(Rgb::new(146, 92, 58)),
    },
    IndexedPaletteEntry {
        key: 'K',
        colour: Some(Rgb::new(231, 163, 104)),
    },
    IndexedPaletteEntry {
        key: 'h',
        colour: Some(Rgb::new(255, 222, 160)),
    },
    IndexedPaletteEntry {
        key: 'w',
        colour: Some(Rgb::new(176, 178, 168)),
    },
    IndexedPaletteEntry {
        key: 'W',
        colour: Some(Rgb::new(238, 238, 228)),
    },
    IndexedPaletteEntry {
        key: 'c',
        colour: Some(Rgb::new(62, 52, 28)),
    },
    IndexedPaletteEntry {
        key: 'C',
        colour: Some(Rgb::new(126, 106, 58)),
    },
    IndexedPaletteEntry {
        key: 'l',
        colour: Some(Rgb::new(214, 176, 86)),
    },
    IndexedPaletteEntry {
        key: 'm',
        colour: Some(Rgb::new(118, 128, 132)),
    },
    IndexedPaletteEntry {
        key: 'M',
        colour: Some(Rgb::new(206, 216, 214)),
    },
    IndexedPaletteEntry {
        key: 'd',
        colour: Some(Rgb::new(86, 58, 36)),
    },
    IndexedPaletteEntry {
        key: 'D',
        colour: Some(Rgb::new(150, 100, 54)),
    },
    IndexedPaletteEntry {
        key: 'a',
        colour: Some(Rgb::new(48, 183, 190)),
    },
    IndexedPaletteEntry {
        key: 'e',
        colour: Some(Rgb::new(112, 220, 255)),
    },
    IndexedPaletteEntry {
        key: 'p',
        colour: Some(Rgb::new(200, 180, 137)),
    },
    IndexedPaletteEntry {
        key: 'P',
        colour: Some(Rgb::new(240, 223, 175)),
    },
    IndexedPaletteEntry {
        key: 's',
        colour: Some(Rgb::new(166, 78, 85)),
    },
];

const RUNEWRIGHT_WORKING_A: &[&str] = &[
    "................",
    "......oooo......",
    ".....ocCCCco....",
    "....ocCCCCCCo...",
    "...ocCllllCCco..",
    "...ocCCCCCCCco..",
    "...ocKhhKKKKco..",
    "...ocKoKKoKKco..",
    "...ocKKKKKKKco..",
    "...ocwWWWWWwco..",
    "....owWWWWWwo...",
    ".....owWWWwo....",
    ".mMMm.ocCCCco...",
    ".mMMmocKCCCcKo..",
    "..Dd.ocKMMMMMo..",
    "..DdKocMmmMmmMo.",
    ".....ocMmeMmmMo.",
    ".....ocMmmmmMKo.",
    ".....olllllllo..",
    "......oddddo....",
    ".....oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const RUNEWRIGHT_WORKING_B: &[&str] = &[
    "................",
    "......oooo......",
    ".....ocCCCco....",
    "....ocCCCCCCo...",
    "...ocCllllCCco..",
    "...ocCCCCCCCco..",
    "...ocKhhKKKKco..",
    "...ocKoKKoKKco..",
    "...ocKKKKKKKco..",
    "...ocwWWWWWwco..",
    "....owWWWWWwo...",
    ".....owWWWwo....",
    "......ocCCCco...",
    "...mMMmCCCCcKo..",
    "...mMMmKMMMMMo..",
    "....DdKMmmMmmMo.",
    "....Dd.MmeMmmMo.",
    ".....ocMmmmmMKo.",
    ".....olllllllo..",
    "......oddddo....",
    ".....oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const RUNEWRIGHT_COUNSEL_RAISE: &[&str] = &[
    "................",
    "......oooo......",
    ".....ocCCCco....",
    "....ocCCCCCCo...",
    "...ocCllllCCco..",
    "...ocCCCCCCCco..",
    "...ocKhhKKKKco..",
    "...ocKoKKoKKco..",
    "...ocKKKKKKKco..",
    "...ocwWWWWWwco..",
    ".Kh.owWWWWWwo...",
    ".KK..owWWWwo....",
    "..ooocCCCCco....",
    ".....ocCCCCcco..",
    ".....ocKMMMMMo..",
    ".mMMmocMmmMmmMo.",
    ".mMMmocMmeMmmMo.",
    "..Dd.ocMmmmmMKo.",
    "..Dd.olllllllo..",
    "......oddddo....",
    ".....oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const RUNEWRIGHT_COUNSEL_WAIT: &[&str] = &[
    "................",
    "......oooo......",
    ".....ocCCCco....",
    "....ocCCCCCCo...",
    "...ocCllllCCco..",
    "...ocCCCCCCCco..",
    "...ocKhhKKKKco..",
    "...ocKoKKoKKco..",
    "...ocKKKKKKKco..",
    "...ocwWWWWWwco..",
    "....owWWWWWwo...",
    ".....owWWWwo....",
    "......ocCCCco...",
    ".....ocCCCCcco..",
    ".....ocKMMMMMo..",
    ".mMMmocMmmMmmMo.",
    ".mMMmocMmeMmmMo.",
    "..Dd.ocMmmmmMKo.",
    "..Dd.olllllllo..",
    "......oddddo....",
    ".....oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const RUNEWRIGHT_SPOILS: &[&str] = &[
    "................",
    "......oooo......",
    ".....ocCCCco....",
    "....ocCCCCCCo...",
    "...ocCllllCCco..",
    "...ocCCCCCCCco..",
    "...ocKhhKKKKco..",
    "...ocKoKKoKKco..",
    "...ocKKKKKKKco..",
    "...ocwWWWWWwco..",
    "....owWWWWWwo...",
    ".....owWWWwo....",
    "......ocCCCco...",
    ".....ocCCCCcco..",
    ".....ocKMMMMMo..",
    ".mMMmocMmmMmmMo.",
    ".mMMmocMssMssMo.",
    "..Dd.ocMmmmmMKo.",
    "..Dd.olllllllo..",
    "......oddddo....",
    ".....oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const RUNEWRIGHT_RESTING: &[&str] = &[
    "................",
    "......oooo......",
    ".....ocCCCco....",
    "....ocCCCCCCo...",
    "...ocCllllCCco..",
    "...ocCCCCCCCco..",
    "...ocKhhKKKKco..",
    "...ocKoKKoKKco..",
    "...ocKKKKKKKco..",
    "...ocwWWWWWwco..",
    "....owWWWWWwo...",
    ".....owWWWwo....",
    "......ocCCCco...",
    ".....ocCCCCcco..",
    ".....ocKMMMMMo..",
    ".mMMmocMmmMmmMo.",
    ".mMMmocMmeMmmMo.",
    "..Dd.ocMmmmmMKo.",
    "..Dd.olllllllo..",
    "......oddddo....",
    ".....oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const RUNEWRIGHT_UNKNOWN: &[&str] = &[
    "................",
    "......oooo......",
    ".....ocCCCco....",
    "....ocCCCCCCo...",
    "...ocCllllCCco..",
    "...ocCCCCCCCco..",
    "...ocKhhKKKKco..",
    "...ocKoKKKKKco..",
    "...ocKKKKoKKco..",
    "...ocwWWWWWwco..",
    "....owWWWWWwo...",
    ".....owWWWwo....",
    "......ocCCCco...",
    ".....ocCCCCcco..",
    ".....ocKMMMMMo..",
    ".mMMmocMmmMmmMo.",
    ".mMMmocMmeMmmMo.",
    "..Dd.ocMmmmmMKo.",
    "..Dd.olllllllo..",
    "......oddddo....",
    ".....oDd..dDo...",
    ".....ooo..ooo...",
    "................",
    "................",
];

const RUNEWRIGHT_SETTLED: &[&str] = &[
    "................",
    "......oooo......",
    ".....ocCCCco....",
    "....ocCCCCCCo...",
    "...ocCllllCCco..",
    "...ocCCCCCCCco..",
    "...ocKhhKKKKco..",
    "...ocKoKKoKKco..",
    "...ocKKKKKKKco..",
    "...ocwWWWWWwco..",
    "....owWWWWWwo...",
    ".....owWWWwo....",
    "......ocCCCco...",
    ".....ocCCCCcco..",
    ".....ocCCCCCCco.",
    ".mMMmocKCCClKCo.",
    ".mMMmocCCCCCCco.",
    "..Dd.ocCCCCCCo..",
    "..Dd.olllllllo..",
    "..Dd.Mooddddo...",
    "..Dd.MsMd..dDo..",
    ".....ooo..ooo...",
    "................",
    "................",
];

pub(super) const RUNEWRIGHT: ClassArt = ClassArt {
    palette: RUNEWRIGHT_PALETTE,
    frames: [
        RUNEWRIGHT_WORKING_A,
        RUNEWRIGHT_WORKING_B,
        RUNEWRIGHT_COUNSEL_RAISE,
        RUNEWRIGHT_COUNSEL_WAIT,
        RUNEWRIGHT_SPOILS,
        RUNEWRIGHT_RESTING,
        RUNEWRIGHT_UNKNOWN,
        RUNEWRIGHT_SETTLED,
    ],
    roster: None,
};
